export const qk = {
  dashboard: ["dashboard"] as const,
  systems: ["systems"] as const,
  system: (id: string) => ["systems", id] as const,
  environments: (systemId: string) => ["systems", systemId, "environments"] as const,
  environment: (id: string) => ["environments", id] as const,
  endpoints: (environmentId: string) => ["environments", environmentId, "endpoints"] as const,
  endpoint: (id: string) => ["endpoints", id] as const,
  rules: (endpointId: string) => ["endpoints", endpointId, "rules"] as const,
  webhooks: (environmentId: string) => ["environments", environmentId, "webhooks"] as const,
  webhook: (id: string) => ["webhooks", id] as const,
  credentials: (environmentId: string) => ["environments", environmentId, "credentials"] as const,
  requestLogs: (query?: unknown) => ["request-logs", query] as const,
  requestLog: (id: string) => ["request-logs", id] as const,
  webhookDeliveries: (query?: unknown) => ["webhook-deliveries", query] as const,
  inboundLogs: (query?: unknown) => ["inbound-webhook-logs", query] as const,
  inboundLog: (id: string) => ["inbound-webhook-logs", id] as const,
  team: ["team"] as const,
};
